FROM cypress/base:12.14.0

RUN mkdir /app
WORKDIR /app

COPY . /app
RUN npm install

RUN $(npm bin)/cypress verify

CMD ["npx percy exec -- cypress run --spec cypress/integration/Spain/**/* --record --key a1776ea6-8468-4997-871e-52e94fd7b9f8"]



